// Generated by gencpp from file smach_tutorials/TestGoal.msg
// DO NOT EDIT!


#ifndef SMACH_TUTORIALS_MESSAGE_TESTGOAL_H
#define SMACH_TUTORIALS_MESSAGE_TESTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smach_tutorials
{
template <class ContainerAllocator>
struct TestGoal_
{
  typedef TestGoal_<ContainerAllocator> Type;

  TestGoal_()
    : goal(0.0)  {
    }
  TestGoal_(const ContainerAllocator& _alloc)
    : goal(0.0)  {
  (void)_alloc;
    }



   typedef double _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::smach_tutorials::TestGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smach_tutorials::TestGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TestGoal_

typedef ::smach_tutorials::TestGoal_<std::allocator<void> > TestGoal;

typedef boost::shared_ptr< ::smach_tutorials::TestGoal > TestGoalPtr;
typedef boost::shared_ptr< ::smach_tutorials::TestGoal const> TestGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smach_tutorials::TestGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smach_tutorials::TestGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smach_tutorials::TestGoal_<ContainerAllocator1> & lhs, const ::smach_tutorials::TestGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smach_tutorials::TestGoal_<ContainerAllocator1> & lhs, const ::smach_tutorials::TestGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smach_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smach_tutorials::TestGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smach_tutorials::TestGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smach_tutorials::TestGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smach_tutorials::TestGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smach_tutorials::TestGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smach_tutorials::TestGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smach_tutorials::TestGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96f1fc969cebfe9056357b5db1aa501e";
  }

  static const char* value(const ::smach_tutorials::TestGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96f1fc969cebfe90ULL;
  static const uint64_t static_value2 = 0x56357b5db1aa501eULL;
};

template<class ContainerAllocator>
struct DataType< ::smach_tutorials::TestGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smach_tutorials/TestGoal";
  }

  static const char* value(const ::smach_tutorials::TestGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smach_tutorials::TestGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64 goal\n"
;
  }

  static const char* value(const ::smach_tutorials::TestGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smach_tutorials::TestGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smach_tutorials::TestGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smach_tutorials::TestGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    Printer<double>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMACH_TUTORIALS_MESSAGE_TESTGOAL_H
