; Auto-generated. Do not edit!


(cl:in-package smach_tutorials-msg)


;//! \htmlinclude TestResult.msg.html

(cl:defclass <TestResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TestResult (<TestResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name smach_tutorials-msg:<TestResult> is deprecated: use smach_tutorials-msg:TestResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestResult>) ostream)
  "Serializes a message object of type '<TestResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestResult>) istream)
  "Deserializes a message object of type '<TestResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestResult>)))
  "Returns string type for a message object of type '<TestResult>"
  "smach_tutorials/TestResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestResult)))
  "Returns string type for a message object of type 'TestResult"
  "smach_tutorials/TestResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestResult>)))
  "Returns md5sum for a message object of type '<TestResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestResult)))
  "Returns md5sum for a message object of type 'TestResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestResult>)))
  "Returns full string definition for message of type '<TestResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestResult)))
  "Returns full string definition for message of type 'TestResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TestResult
))
