; Auto-generated. Do not edit!


(cl:in-package smach_tutorials-msg)


;//! \htmlinclude TestFeedback.msg.html

(cl:defclass <TestFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TestFeedback (<TestFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name smach_tutorials-msg:<TestFeedback> is deprecated: use smach_tutorials-msg:TestFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestFeedback>) ostream)
  "Serializes a message object of type '<TestFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestFeedback>) istream)
  "Deserializes a message object of type '<TestFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestFeedback>)))
  "Returns string type for a message object of type '<TestFeedback>"
  "smach_tutorials/TestFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestFeedback)))
  "Returns string type for a message object of type 'TestFeedback"
  "smach_tutorials/TestFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestFeedback>)))
  "Returns md5sum for a message object of type '<TestFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestFeedback)))
  "Returns md5sum for a message object of type 'TestFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestFeedback>)))
  "Returns full string definition for message of type '<TestFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestFeedback)))
  "Returns full string definition for message of type 'TestFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TestFeedback
))
