; Auto-generated. Do not edit!


(cl:in-package smach_tutorials-msg)


;//! \htmlinclude TestGoal.msg.html

(cl:defclass <TestGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:float
    :initform 0.0))
)

(cl:defclass TestGoal (<TestGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name smach_tutorials-msg:<TestGoal> is deprecated: use smach_tutorials-msg:TestGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <TestGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader smach_tutorials-msg:goal-val is deprecated.  Use smach_tutorials-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestGoal>) ostream)
  "Serializes a message object of type '<TestGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestGoal>) istream)
  "Deserializes a message object of type '<TestGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'goal) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestGoal>)))
  "Returns string type for a message object of type '<TestGoal>"
  "smach_tutorials/TestGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestGoal)))
  "Returns string type for a message object of type 'TestGoal"
  "smach_tutorials/TestGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestGoal>)))
  "Returns md5sum for a message object of type '<TestGoal>"
  "96f1fc969cebfe9056357b5db1aa501e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestGoal)))
  "Returns md5sum for a message object of type 'TestGoal"
  "96f1fc969cebfe9056357b5db1aa501e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestGoal>)))
  "Returns full string definition for message of type '<TestGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestGoal)))
  "Returns full string definition for message of type 'TestGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TestGoal
    (cl:cons ':goal (goal msg))
))
