(cl:defpackage armor_msgs-srv
  (:use )
  (:export
   "ARMORDIRECTIVE"
   "<ARMORDIRECTIVE-REQUEST>"
   "ARMORDIRECTIVE-REQUEST"
   "<ARMORDIRECTIVE-RESPONSE>"
   "ARMORDIRECTIVE-RESPONSE"
   "ARMORDIRECTIVELIST"
   "<ARMORDIRECTIVELIST-REQUEST>"
   "ARMORDIRECTIVELIST-REQUEST"
   "<ARMORDIRECTIVELIST-RESPONSE>"
   "ARMORDIRECTIVELIST-RESPONSE"
  ))

