// Generated by gencpp from file armor_msgs/ArmorDirectiveList.msg
// DO NOT EDIT!


#ifndef ARMOR_MSGS_MESSAGE_ARMORDIRECTIVELIST_H
#define ARMOR_MSGS_MESSAGE_ARMORDIRECTIVELIST_H

#include <ros/service_traits.h>


#include <armor_msgs/ArmorDirectiveListRequest.h>
#include <armor_msgs/ArmorDirectiveListResponse.h>


namespace armor_msgs
{

struct ArmorDirectiveList
{

typedef ArmorDirectiveListRequest Request;
typedef ArmorDirectiveListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmorDirectiveList
} // namespace armor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armor_msgs::ArmorDirectiveList > {
  static const char* value()
  {
    return "c8f7a3567fd279dae5ca45853049f5a7";
  }

  static const char* value(const ::armor_msgs::ArmorDirectiveList&) { return value(); }
};

template<>
struct DataType< ::armor_msgs::ArmorDirectiveList > {
  static const char* value()
  {
    return "armor_msgs/ArmorDirectiveList";
  }

  static const char* value(const ::armor_msgs::ArmorDirectiveList&) { return value(); }
};


// service_traits::MD5Sum< ::armor_msgs::ArmorDirectiveListRequest> should match
// service_traits::MD5Sum< ::armor_msgs::ArmorDirectiveList >
template<>
struct MD5Sum< ::armor_msgs::ArmorDirectiveListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armor_msgs::ArmorDirectiveList >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armor_msgs::ArmorDirectiveListRequest> should match
// service_traits::DataType< ::armor_msgs::ArmorDirectiveList >
template<>
struct DataType< ::armor_msgs::ArmorDirectiveListRequest>
{
  static const char* value()
  {
    return DataType< ::armor_msgs::ArmorDirectiveList >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armor_msgs::ArmorDirectiveListResponse> should match
// service_traits::MD5Sum< ::armor_msgs::ArmorDirectiveList >
template<>
struct MD5Sum< ::armor_msgs::ArmorDirectiveListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armor_msgs::ArmorDirectiveList >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armor_msgs::ArmorDirectiveListResponse> should match
// service_traits::DataType< ::armor_msgs::ArmorDirectiveList >
template<>
struct DataType< ::armor_msgs::ArmorDirectiveListResponse>
{
  static const char* value()
  {
    return DataType< ::armor_msgs::ArmorDirectiveList >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMOR_MSGS_MESSAGE_ARMORDIRECTIVELIST_H
