// Generated by gencpp from file armor_msgs/ArmorDirectiveRequest.msg
// DO NOT EDIT!


#ifndef ARMOR_MSGS_MESSAGE_ARMORDIRECTIVEREQUEST_H
#define ARMOR_MSGS_MESSAGE_ARMORDIRECTIVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <armor_msgs/ArmorDirectiveReq.h>

namespace armor_msgs
{
template <class ContainerAllocator>
struct ArmorDirectiveRequest_
{
  typedef ArmorDirectiveRequest_<ContainerAllocator> Type;

  ArmorDirectiveRequest_()
    : armor_request()  {
    }
  ArmorDirectiveRequest_(const ContainerAllocator& _alloc)
    : armor_request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::armor_msgs::ArmorDirectiveReq_<ContainerAllocator>  _armor_request_type;
  _armor_request_type armor_request;





  typedef boost::shared_ptr< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmorDirectiveRequest_

typedef ::armor_msgs::ArmorDirectiveRequest_<std::allocator<void> > ArmorDirectiveRequest;

typedef boost::shared_ptr< ::armor_msgs::ArmorDirectiveRequest > ArmorDirectiveRequestPtr;
typedef boost::shared_ptr< ::armor_msgs::ArmorDirectiveRequest const> ArmorDirectiveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator1> & lhs, const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.armor_request == rhs.armor_request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator1> & lhs, const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dd786c47e3f813a5233dff98bbcad0d";
  }

  static const char* value(const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dd786c47e3f813aULL;
  static const uint64_t static_value2 = 0x5233dff98bbcad0dULL;
};

template<class ContainerAllocator>
struct DataType< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armor_msgs/ArmorDirectiveRequest";
  }

  static const char* value(const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmorDirectiveReq armor_request\n"
"\n"
"================================================================================\n"
"MSG: armor_msgs/ArmorDirectiveReq\n"
"string client_name\n"
"string reference_name\n"
"string command\n"
"string primary_command_spec\n"
"string secondary_command_spec\n"
"string[] args\n"
;
  }

  static const char* value(const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.armor_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmorDirectiveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armor_msgs::ArmorDirectiveRequest_<ContainerAllocator>& v)
  {
    s << indent << "armor_request: ";
    s << std::endl;
    Printer< ::armor_msgs::ArmorDirectiveReq_<ContainerAllocator> >::stream(s, indent + "  ", v.armor_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMOR_MSGS_MESSAGE_ARMORDIRECTIVEREQUEST_H
