// Generated by gencpp from file armor_msgs/ArmorDirective.msg
// DO NOT EDIT!


#ifndef ARMOR_MSGS_MESSAGE_ARMORDIRECTIVE_H
#define ARMOR_MSGS_MESSAGE_ARMORDIRECTIVE_H

#include <ros/service_traits.h>


#include <armor_msgs/ArmorDirectiveRequest.h>
#include <armor_msgs/ArmorDirectiveResponse.h>


namespace armor_msgs
{

struct ArmorDirective
{

typedef ArmorDirectiveRequest Request;
typedef ArmorDirectiveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmorDirective
} // namespace armor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armor_msgs::ArmorDirective > {
  static const char* value()
  {
    return "39cbf11e18dc47e2c7b5fda84e5d8c39";
  }

  static const char* value(const ::armor_msgs::ArmorDirective&) { return value(); }
};

template<>
struct DataType< ::armor_msgs::ArmorDirective > {
  static const char* value()
  {
    return "armor_msgs/ArmorDirective";
  }

  static const char* value(const ::armor_msgs::ArmorDirective&) { return value(); }
};


// service_traits::MD5Sum< ::armor_msgs::ArmorDirectiveRequest> should match
// service_traits::MD5Sum< ::armor_msgs::ArmorDirective >
template<>
struct MD5Sum< ::armor_msgs::ArmorDirectiveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armor_msgs::ArmorDirectiveRequest> should match
// service_traits::DataType< ::armor_msgs::ArmorDirective >
template<>
struct DataType< ::armor_msgs::ArmorDirectiveRequest>
{
  static const char* value()
  {
    return DataType< ::armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armor_msgs::ArmorDirectiveResponse> should match
// service_traits::MD5Sum< ::armor_msgs::ArmorDirective >
template<>
struct MD5Sum< ::armor_msgs::ArmorDirectiveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armor_msgs::ArmorDirectiveResponse> should match
// service_traits::DataType< ::armor_msgs::ArmorDirective >
template<>
struct DataType< ::armor_msgs::ArmorDirectiveResponse>
{
  static const char* value()
  {
    return DataType< ::armor_msgs::ArmorDirective >::value();
  }
  static const char* value(const ::armor_msgs::ArmorDirectiveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMOR_MSGS_MESSAGE_ARMORDIRECTIVE_H
