// Generated by gencpp from file armor_msgs/QueryItem.msg
// DO NOT EDIT!


#ifndef ARMOR_MSGS_MESSAGE_QUERYITEM_H
#define ARMOR_MSGS_MESSAGE_QUERYITEM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armor_msgs
{
template <class ContainerAllocator>
struct QueryItem_
{
  typedef QueryItem_<ContainerAllocator> Type;

  QueryItem_()
    : key()
    , value()  {
    }
  QueryItem_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::armor_msgs::QueryItem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armor_msgs::QueryItem_<ContainerAllocator> const> ConstPtr;

}; // struct QueryItem_

typedef ::armor_msgs::QueryItem_<std::allocator<void> > QueryItem;

typedef boost::shared_ptr< ::armor_msgs::QueryItem > QueryItemPtr;
typedef boost::shared_ptr< ::armor_msgs::QueryItem const> QueryItemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armor_msgs::QueryItem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armor_msgs::QueryItem_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armor_msgs::QueryItem_<ContainerAllocator1> & lhs, const ::armor_msgs::QueryItem_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armor_msgs::QueryItem_<ContainerAllocator1> & lhs, const ::armor_msgs::QueryItem_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armor_msgs::QueryItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armor_msgs::QueryItem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armor_msgs::QueryItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armor_msgs::QueryItem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armor_msgs::QueryItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armor_msgs::QueryItem_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armor_msgs::QueryItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf57fdc6617a881a88c16e768132149c";
  }

  static const char* value(const ::armor_msgs::QueryItem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf57fdc6617a881aULL;
  static const uint64_t static_value2 = 0x88c16e768132149cULL;
};

template<class ContainerAllocator>
struct DataType< ::armor_msgs::QueryItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armor_msgs/QueryItem";
  }

  static const char* value(const ::armor_msgs::QueryItem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armor_msgs::QueryItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n"
"string value\n"
;
  }

  static const char* value(const ::armor_msgs::QueryItem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armor_msgs::QueryItem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryItem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armor_msgs::QueryItem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armor_msgs::QueryItem_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMOR_MSGS_MESSAGE_QUERYITEM_H
